### ISSUE TITLE
New 4.0.0 beta ?

### ISSUE THREAD

**Issue by johncrim** [oddbird/accoutrement#102]
Hi:

When possible, could you please release a new 4.0.0 beta of Accoutrement? We'd like to switch to it - I'm pretty sure the kinks are worked out with the recent PRs, and if not I'd like to help uncover them.

Thank you!

**Comment by johncrim** [comment]
Hi @mirisuzanne and @jgerigmeyer - I'm positive you're both extremely busy, just pinging you in hopes that building a new beta is easy.

**Comment by mirisuzanne** [comment]
@johncrim beta-4 should be available now, at the npm pre tag. Let us know if you have any other issues!
