### ISSUE TITLE
Under very specific conditions, long-hand adjustment maps produce incorrect results

### ISSUE THREAD

**Issue by joelschou** [oddbird/accoutrement#31]
Hi! I've encountered something very odd and very specific. I have a large map and am using the long-hand syntax for functional adjustments -- in this case, to colors. For whatever reason, the adjustments are being applied in the wrong order to to a few items in the map. I wasn't able to reproduce the issue inside the test suite for Accoutrement, but I did create a small standalone test that's consistently frustrating. 

https://github.com/joelschou/accoutrement2-test2

I'll keep digging to see if I can figure out why it's doing this.

Edit: I just discovered at least one particular factor: I have registered the SASS `lighten` function so I can use it in my map adjustments. If I instead use `shade`, which is built into Accoutrement, the issue goes away (obviously, `lighten` and `shade` do different things, but I just tested it quick).

**Comment by mirisuzanne** [comment]
good catch! want to submit a PR patch?

**Comment by joelschou** [comment]
By sheer coincidence, you noticed the opposite problem years ago:
https://github.com/sass/libsass/issues/556

**Comment by joelschou** [comment]
(Also by sheer coincidence, I found that issue as you were commenting here)

**Comment by mirisuzanne** [comment]
ha, that's funny. Maps are ordered in Sass, I wonder why comparisons aren't. Though, as I say in that thread: there are many unordered use-cases. Even most accoutrement use-cases are order-agnostic.
