### ISSUE TITLE
Issues with latest versions of dart-sass

### ISSUE THREAD

**Issue by jcamilleri13** [oddbird/accoutrement#36]
I've recently switched to dart-sass for my build pipelines ([https://www.npmjs.com/package/sass](https://www.npmjs.com/package/sass)), however I seem to have hit some problems with Accoutrement's method of converting maps to strings, i.e. using the 'quote' function.

The first instance where this breaks is in _parser.scss, at [line 268](https://github.com/oddbird/accoutrement/blob/a74d177427fdb8805a5cade30b7acadd40f378f4/sass/core/_parser.scss#L268). The simplest solution would be to replace the 'quote' function with the in-built 'inspect' function, which converts the maps successfully without any errors, however I'm uncertain if this is best practice, since inspect() is traditionally meant for debugging.

**Comment by mirisuzanne** [comment]
That sounds fine, do you want to submit a patch?

I'm also curious what the error is. Does `quote()` now require a string in order to work?

**Comment by jcamilleri13** [comment]
Yep, the compiler throws a "$string: (...map) is not a string" error.
I'll test with sass and node-sass and submit a PR soon 👍

**Comment by jgerigmeyer** [comment]
Closed in #37.
