### ISSUE TITLE
Performance issues and "silent" failures

### ISSUE THREAD

**Issue by jcamilleri13** [oddbird/accoutrement#41]
Hi, me again.

I've almost finished fully migrating our internal style framework to Accoutrement, but have bumped into some performance issues as I add more keys to the map. I've identified a few bottlenecks in the `_a_replace()` function, mostly when dealing with large maps. My current map is extremely large (over 2000 keys), which is probably not something that Accoutrement was ever built to cater for, so I understand that what I'm doing is probably not strictly conventional. However I've pinpointed a few optimisations that drastically improve performance, which might be worthwhile additions to the library anyway.

The quickest fix was simply moving the `_a_str-length-sort()` function out of `_a_replace()`, and only sorting once, after the map had been flattened. This resulted in a significant performance improvement. Given that the algorithm still relied on accessing every single key in the map however, I re-wrote it to rely on `map-get()` and `map-has-key()` functionality rather than a linear parse, which improved performance even more as probably removes the need for sorting. Rough benchmarks for the two variants, on a map of ~2000 keys, can be seen here:

|  | 10 `get-token()` operations | 100 `get-token()` operations | 1000 `get-token()` operations |
| - | - | - | - |
| No optimisation | ~15s | ~110s | ~1000s |
| Single `_a_str-length-sort()` | ~12s | ~15s | ~50s |
| Improved algorithm | ~5s | ~6s | ~12s |

Naturally, I'd recommend the rewritten algorithm – every second counts when you're trying to prototype using a live-reload system – but shifting the sort function is also a marked improvement. Writing the algorithm brought something else to my attention though: how accoutrement handles missing keys. The current mechanism seems to favour failing silently when a nested key doesn't exist, either by injecting an entire map as a string into the returned value or returning the original key. I don't quite understand the intended use case for this behaviour, however. In most other programming languages, a user would expect an error to be thrown if an attempt is made to retrieve a key that isn't there. Even more so in a compiled-language scenario, where, generally, attempting to retrieve a key not in the map is a typographical user-error where the incorrect key was passed as a parameter to the `get-token()` function. Now the faster algorithm can be tweaked to handle the missing key cases as before, but I was wondering if having missing nested keys should be considered an error. Perhaps if not by default, we could have a configurable "strict mode" which would cause it to fail?

Thought I'd get your opinion on it and perhaps I could submit a PR or share the rewritten code for review.

Thanks a million!

**Comment by mirisuzanne** [comment]
Hi @jcamilleri13 - thanks for digging into this!

I think we fail silently so as not to break every single instance of `#` inside existing maps. I'm open to other ways of solving that - because otherwise I totally agree.

I'd love to see a PR of these performance improvements!

**Comment by jcamilleri13** [comment]
The way I handled it to keep the existing unit tests from breaking was by adding an internal configuration flag that would default strict mode to false. If you flip it to true it will throw an error if the key isn't found, otherwise it'll default to the previous behaviour, so it can be used on new projects without being a breaking change.

I'll double check all the other unit tests are passing with the change and try write a couple of new ones to handle the strict flag. As soon as that's done I'll make the pull request and we can take it from there. :)

**Comment by jcamilleri13** [comment]
Corrected by #42. :)
