### ISSUE TITLE
A function has already been registered under the name `remove-nth`"

### ISSUE THREAD

**Issue by sunil-jhamnani** [oddbird/accoutrement#51]
I am not sure if I have messed up something or its an actual issue. The complete stack trace on my terminal is this

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
                                             
           @return _a_error($error, $origin);
                                            ^
      "[_a_register-function] A function has already been registered under the name `remove-nth`"
                                            ╷
210 │       @return _a_error($error, $origin);
    │               ^^^^^^^^^^^^^^^^^^^^^^^^^
                                            ╵
  ../packages/accoutrement/node_modules/accoutrement/sass/core/_register.scss 210:15  -a-registration()
  ../packages/accoutrement/node_modules/accoutrement/sass/core/_register.scss 144:14  -a-register-function()
  ../packages/accoutrement/node_modules/accoutrement/sass/core/_lists.scss 65:1       @import
  ../packages/accoutrement/node_modules/accoutrement/sass/_core.scss 37:9             @import
  ../packages/accoutrement/node_modules/accoutrement/sass/_tools.scss 4:9             @import
  ../packages/accoutrement/node_modules/accoutrement/sass/_index.scss 4:9             @import
  ../packages/accoutrement/src/index.scss 1:9                                         @import
  ../packages/uikit/design.scss 3:9                                                   @import
  stdin 2:9                                                                           root stylesheet
      in /<path-to>/projects/uikit/packages/accoutrement/node_modules/accoutrement/sass/core/_register.scss (line 210, column 15)
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
```

**Brief on this**
I am importing accoutrement in one of my module with the same name(name is in test phase, will change it once developed). The import statement looks like this
`@import '../node_modules/accoutrement/sass/tools';`

I don't understand why the function **remove-nth** is getting registered twice. I checked the code and found only 1 place from where its getting registered. 
`sass/core/_lists.scss: line 65`
`@include _a_register-function('_a_remove-nth', 'remove-nth');`

Thats the only place from where it is getting called. 

Can someone help me why I am facing this issue?

**Comment by mirisuzanne** [comment]
Interesting, I haven't run into that before, and would have to do some more testing. Are you using Dart Sass modules? If so, have you tried `@use` in place of `@import`?

The `@use` syntax ensures that Accoutrement will only be processed once per compilation. Using `@import`, it's possible that Accoutrement is being processed twice?

**Comment by sunil-jhamnani** [comment]
Yes I am using Dart Sass modules. 
Also I tried using `@use` like this `@use '../node_modules/accoutrement/sass/index';` but its not working. Giving me undefined for mixins and functions. Eg:
```
@include add-colors($base-colors);
                                 ^
                             Undefined mixin.
```

**Comment by sunil-jhamnani** [comment]
@mirisuzanne 
So the issue is fixed. The index file was getting imported more then once and that was the reason for that error. 
Still i was thinking if I can use `@use` to use the `index.scss` file so that by any chance this error doesn't show up again.

**Comment by mirisuzanne** [comment]
You should be able to use the index, though generally I would do that implicitly. If  you `@use` a directory, it will automatically get the index file: 

```scss
@use '../node_modules/accoutrement/sass';
```

You could also be having namespace issues. Modules are loaded into a namespace based on the last fragment of the path name (`index` or `sass`) unless you override it explicitly. So:

```scss
@use '../node_modules/accoutrement/sass/index';
@include index.add-colors($base-colors);
```

or:

```scss
@use '../node_modules/accoutrement/sass' as accoutrement;
@include accoutrement.add-colors($base-colors);
```
