### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/accoutrement#69]
Travis is still running against node v8, but support was dropped in https://github.com/oddbird/accoutrement/releases/tag/v3.0.0

**Comment by mirisuzanne** [comment]
Interesting, why did my PRs all show passing tests?

**Comment by jgerigmeyer** [comment]
> Interesting, why did my PRs all show passing tests?

We didn't have Travis setup as a GH app, so it wasn't reporting here. Fixed now.
